# Generated by Django 3.2.7 on 2022-01-16 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='otp',
        ),
    ]
