# Generated by Django 3.2.7 on 2022-01-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220120_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(default='Maths', max_length=50),
        ),
    ]
