# Generated by Django 3.2.7 on 2022-01-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_book_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
